//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okul_sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OgrId { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public Nullable<int> OgrNo { get; set; }
        public string OgrBolum { get; set; }
        public Nullable<decimal> OgrKredi { get; set; }
    }
}
